import React from 'react';

const HowToInterview = (props) => {
        return (
            <div className="employment-blog">
                <p>
                I don’t know how many interviews I’ve done since I finished university last year in 2020, but it’s probably somewhere between 25 and 30. The first few were terrible. By maybe about the fifth one, I was starting to slowly come to terms with how terrible I was at this. By number ten, the sense of nervousness was receding, and I was just bad at interviews without being nervous about it. By number 15 I was getting slightly less bad. By the third month I realised that the interviews were actually going well, and I was actually coming very close to getting a job (which ironically made me a bit nervous again). In the end, I received four job offers in two weeks, and had the luxury of being able to take my pick. Something they don’t tell you is that interviewing is a skill, and like with any new skill, the vast majority of people are terrible at it when they first start doing it. I was one of these people. I’m here to tell you that it’s possible to survive the experience of being terrible at job interviews and to still go on to find the perfect job for you.
                </p>
                <div className="code-blog-entry-content-img">
                    <figure>
                    <img src={'images/blog-interviews/tunnel.jpg'} alt="Light at the End of the Tunnel" height='100%' width='100%' />
                    </figure>
                </div>
                <p>
                In this post, I’m going to focus on the specific things I learned during my experience about how to maximise your chances of success in your interviews, which I discovered to really just be conversations verifying for the employer that you are easy to get along with personally, and/or that you can behave professionally — they want to see that you can ‘walk the walk’, after you have ‘talked the talk’ in your CV and application. I’m going to talk about the right mindset and preparation you can bring to a job interview, which is what makes all the difference — it was really the only thing that changed for me, between being terrible and getting no offers for months, and getting four offers in two weeks. My university degree had stayed exactly the same, the only thing that had changed was my mindset and preparation, which are variables that can be controlled over time to improve your interview performance.
                </p>
                <p>
                It’s worth mentioning before proceeding that are already lots of good blogs, articles, and even courses out there giving interview advice, and if you’re job–searching it’s definitely worth your time to have a look for those, but this information here is just what worked for me in my interviews. I also recommend you, if you haven’t already, to check out my last blog post below, entitled “How to Get a Job during a Pandemic”, which gave shorter and broader job–searching tips, centering around the transition process between university education and employment, where I recommended patience, perseverance, and growth as the ways to frame your life in response to the stress and uncertainty that this period can bring. I also gave some tips about how to stay disciplined and how to connect with as many potential employers as possible. If you’ve already read that post, in this one I’m going to dive deeper and give more detailed information about how to do well in a job interview, which is what ultimately wins you the job, after you already have your foot in the door, thanks to your CV, education, and perseverance.
                </p>
                <ol className="extra-top-padding">
                    <li><strong>Make a connection with your interviewer.</strong> At the start of the interview, focus on feeling comfortable and getting on the same page as your interviewer. Just think of them as another person, and see if you can make a human connection. If the interviewer is any good, they will make an effort to make you feel comfortable by asking you about yourself and your life at first, before asking about your skills and qualifications. Furthermore, this is actually oftentimes what interviewers are primarily looking for — to see if you are the kind of person they can connect with. Usually they’ve already seen your qualifications on your CV, so when they ask you questions, they’re really just trying to gauge you as a person, to see if you are the kind of person they and/or their colleagues would enjoy working alongside. If you get the job, this interview could actually instead be better thought of as the start of your working relationship with your company, a relationship that could last years (if they are not a recruiter). This point is really so crucial — as soon as I started to see my interviewers as just people I was doing business with, rather than authority figures that I wanted something from, my interviews started going way better. However, always pay attention to not only what your interviewer is saying, but <em>how</em> they are saying it, and adapt your behaviour to the tone of the interaction. For example, does it seem right to speak in a professional manner, answering questions succinctly and waiting for the next one, or does this interviewer seem more informal and chatty?</li>
                    <li><strong>Trust and respect yourself, while still being humble.</strong> This is the right vibe to have in many scenarios, but especially in a job interview. Companies want to have an employee who clearly believes in themselves and can talk about their past successes, but is also grateful for the opportunity. They want someone who knows that they would be an awesome employee, but who doesn’t believe that they’re better than other people. You may have to tweak this point based on your personality: if you’re the kind of person who doesn’t usually give yourself much credit, you should practice writing down the relevant things you are proud of about yourself, and be prepared to talk about them when asked. However, if self–confidence is not really a problem for you, then your concern should be to make sure that you don’t brag too much in the interview and/or give off the vibe that you’ll probably be running the company in a couple of years. Always finish an interview with “Thank you very much for the interview John, and whatever decision you make, I appreciate your time today and look forward to hearing from you.” Being respectful and having a good attitude is exactly the kind of energy employers look for, if they have it themselves.</li>
                </ol>
                <div className="code-blog-entry-content-img">
                    <figure>
                        <img src={'images/blog-interviews/white-wolf.jpg'} alt="White Wolf" height='100%' width='100%'/>
                    </figure>
                    <figcaption>2.5: Channel this strong beautiful creature as you get better at interviews.</figcaption>
                </div>
                <ol start="3">
                    <li><strong>Don’t think of the ‘failures’ as failures — they are training.</strong> If you do an interview and the company gets back to you with bad news, or if they tell you right there after the interview that you were unsuccessful, don’t think of it as a bad thing. Think of it as a necessary thing. Think of it as a good thing. Think of it the same way you would think of a difficult session in the gym. You’re now a little bit smarter and more savvy about doing interviews than you were before. Maybe you’ve realised something you did or said wrong, which you now know to not say at the next interview. In any case, your mind is now a little more adapted to the situation of an interview. Of course it hurts being rejected, and I don’t mean to downplay that, but the hurt starts to sting less the more interviews you do, which is why I also recommend doing as many interviews as possible to desensitise yourself to receiving that bad news. Don’t expect a negative response from a company, but be totally prepared to accept it if it does come.</li>
                    <li><strong>Put some time aside in your life for learning and doing interesting projects.</strong> Interviewers and companies <em>love</em> people who are self–motivated, and constantly learning by themselves. They love it from a personality standpoint, because it shows that you’re the kind of person who will try to solve a problem yourself rather than make problems for your colleagues and managers, and they also love it from a business standpoint, because it shows that you’re an asset whose value to the company is going to increase over time. This is also a really good idea for you personally, because it allows you to continue your professional development and skills even though you aren’t yet employed, as well as keeps you busy and gives you something interesting and relevant to share during your interview.</li>
                    <li><strong>Put some time aside for your social life.</strong> Even though you really need a job, don’t forget to schedule that social time in — a healthy social life pays more dividends than anything else. It’s a psychological truism that <a onClick={(event) => event.stopPropagation()} target="_blank" rel="noopener noreferrer" className="cyan" href="https://www.adultdevelopmentstudy.org/">the quality of your life is dictated by the quality of your social relationships</a>. If you isolate yourself from people during your job–search, you’re most likely to end up like Marvin the Paranoid Android, or Eeyore from Winnie The Pooh, and no company wants to hire those guys. If instead you dedicate some of your week to spending time with people who love you, then you’re going to have more energy available to smile a bit more confidently during your interview and to speak a bit more clearly. Go do something you enjoy for a while, at least once or twice a week, with people you like, or give your Mum or your Grandma a phone call (they’ll appreciate that). You want to be in good shape socially, because just like being in good shape physically, people can tell.</li>
                </ol>
                <div className="code-blog-entry-content-img">
                    <figure>
                        <img src={'images/blog-interviews/beach.jpg'} alt="Malibu" height='100%' width='100%'/>
                    </figure>
                    <figcaption>You could also bring your Grandma here</figcaption>
                </div>
                <ol start="6">
                    <li><strong>And finally — how to answer the dreaded “Do you have any questions for us?”</strong> This is always the most intimidating moment of an interview, and the secret is that it’s actually designed to be. Companies want to see how you respond to a bit of pressure. The right way to deal with the question is remaining calm, and being prepared. Before the interview, you should write out a list of questions you genuinely do want to know. Some possible examples: “When would the position start? In which area is the office located? What size is the team in which I would be working? In what timeframe are you thinking of making an offer to the successful candidate?” It doesn’t matter what the questions are, as long as you are truly interested in knowing them, and it’s fine to have them written on a piece of paper with you in the interview, unless your powers of memory are extra amazing. What you will then see is that most of your questions will be naturally answered throughout the course of the interview — and, in fact, depending on the tone of the interaction, there may be opportunities for you to ask your questions as the interview goes. For example, if the interview is not so formal, and the interviewer is talking about the people you will be working with, you could ask, “actually, I was wondering what the size of this team is?” However, don’t worry so much if you don’t get a chance to ask questions, because some interviewers are very structured and strict about how they like their interviews to go. So finally, when you get hit with ‘the’ question at the end, you can just remain calm (already doing better than 90% of people) and ask whatever questions are remaining on your list, and if/when there are none left, simply say, “You’ve actually answered all the questions I had, but if anything else comes up before we next speak, is it okay to send you an email?” And that’s it.</li>
                </ol>
                <p>
                The idea of putting yourself forward for a job interview, to be judged as a person and a potential employee by someone who doesn’t really know you, based on just a few minutes or an hour, and most often these days through a computer screen, can understandably be pretty nerve–wracking. Furthermore, you know that this person is going to be comparing you to other candidates, which can be a bit of an uncomfortable idea. On top of that, you know that there’s a possibility (or perhaps a probability) of failure and rejection, even after all the time, energy, and emotion you’ve invested into the application process for this job. However — the good news is that everyone either is or has been, at some point, in this position. It’s not a question of whether you are good enough. It’s a question of whether you are determined enough to keep going, to keep exploring the opportunities available, and to have faith while you keep putting your best foot forward.
                </p>
                <div className="code-blog-entry-content-img">
                    <figure>
                        <img src={'images/blog-interviews/best-foot-forward.jpg'} alt="Best Foot Forward" height='100%' width='100%'/>
                    </figure>
                    <figcaption>Thanks <a onClick={(event) => event.stopPropagation()} target="_blank" rel="noopener noreferrer" className="cyan" href="https://unsplash.com/@camadams?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Cam Adams</a> for the amazing pictures used in this post.</figcaption>
                </div>
                
            </div>
        )
    }

export default HowToInterview;